[target.x86_64-unknown-linux-musl]
linker = "rust-lld"


[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "debuginfo=0",
    "-C", "link-arg=/DEBUG:NONE",
    "-C", "link-arg=/EMITPOGOPHASEINFO",
    "-C", "strip=symbols"
]
